/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgenticAvatarCreate,
  HTTPValidationError,
  PaginatedResponseAgenticAvatarResponse,
  SuccessResponseAgenticAvatarResponse,
} from '../models/index';
import {
    AgenticAvatarCreateFromJSON,
    AgenticAvatarCreateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PaginatedResponseAgenticAvatarResponseFromJSON,
    PaginatedResponseAgenticAvatarResponseToJSON,
    SuccessResponseAgenticAvatarResponseFromJSON,
    SuccessResponseAgenticAvatarResponseToJSON,
} from '../models/index';

export interface CreateAgenticAvatarRequest {
    agenticAvatarCreate: AgenticAvatarCreate;
}

export interface DeleteAgenticAvatarRequest {
    avatarId: string;
}

export interface GetAgenticAvatarRequest {
    avatarId: string;
}

export interface ListAgenticAvatarsRequest {
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class AgenticAvatarsApi extends runtime.BaseAPI {

    /**
     * Create Agentic Avatar
     */
    async createAgenticAvatarRaw(requestParameters: CreateAgenticAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseAgenticAvatarResponse>> {
        if (requestParameters['agenticAvatarCreate'] == null) {
            throw new runtime.RequiredError(
                'agenticAvatarCreate',
                'Required parameter "agenticAvatarCreate" was null or undefined when calling createAgenticAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/agentic-avatars/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgenticAvatarCreateToJSON(requestParameters['agenticAvatarCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseAgenticAvatarResponseFromJSON(jsonValue));
    }

    /**
     * Create Agentic Avatar
     */
    async createAgenticAvatar(requestParameters: CreateAgenticAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseAgenticAvatarResponse> {
        const response = await this.createAgenticAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Agentic Avatar
     */
    async deleteAgenticAvatarRaw(requestParameters: DeleteAgenticAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['avatarId'] == null) {
            throw new runtime.RequiredError(
                'avatarId',
                'Required parameter "avatarId" was null or undefined when calling deleteAgenticAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/agentic-avatars/{avatar_id}`;
        urlPath = urlPath.replace(`{${"avatar_id"}}`, encodeURIComponent(String(requestParameters['avatarId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Agentic Avatar
     */
    async deleteAgenticAvatar(requestParameters: DeleteAgenticAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteAgenticAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Agentic Avatar
     */
    async getAgenticAvatarRaw(requestParameters: GetAgenticAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseAgenticAvatarResponse>> {
        if (requestParameters['avatarId'] == null) {
            throw new runtime.RequiredError(
                'avatarId',
                'Required parameter "avatarId" was null or undefined when calling getAgenticAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/agentic-avatars/{avatar_id}`;
        urlPath = urlPath.replace(`{${"avatar_id"}}`, encodeURIComponent(String(requestParameters['avatarId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseAgenticAvatarResponseFromJSON(jsonValue));
    }

    /**
     * Get Agentic Avatar
     */
    async getAgenticAvatar(requestParameters: GetAgenticAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseAgenticAvatarResponse> {
        const response = await this.getAgenticAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all user agentic avatars
     * List Avatars
     */
    async listAgenticAvatarsRaw(requestParameters: ListAgenticAvatarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseAgenticAvatarResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/agentic-avatars/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseAgenticAvatarResponseFromJSON(jsonValue));
    }

    /**
     * Get all user agentic avatars
     * List Avatars
     */
    async listAgenticAvatars(requestParameters: ListAgenticAvatarsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseAgenticAvatarResponse> {
        const response = await this.listAgenticAvatarsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
