/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SuccessResponseApiKeyValidationResponse,
} from '../models/index';
import {
    SuccessResponseApiKeyValidationResponseFromJSON,
    SuccessResponseApiKeyValidationResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class APIKeysApi extends runtime.BaseAPI {

    /**
     * Validate an API key and get its details
     * Validate API Key
     */
    async validateApiKeyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseApiKeyValidationResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/api-keys/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseApiKeyValidationResponseFromJSON(jsonValue));
    }

    /**
     * Validate an API key and get its details
     * Validate API Key
     */
    async validateApiKey(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseApiKeyValidationResponse> {
        const response = await this.validateApiKeyRaw(initOverrides);
        return await response.value();
    }

}
