/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  PaginatedResponseAvatarResponse,
  SuccessResponseAvatarDeleteResponse,
  SuccessResponseAvatarResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PaginatedResponseAvatarResponseFromJSON,
    PaginatedResponseAvatarResponseToJSON,
    SuccessResponseAvatarDeleteResponseFromJSON,
    SuccessResponseAvatarDeleteResponseToJSON,
    SuccessResponseAvatarResponseFromJSON,
    SuccessResponseAvatarResponseToJSON,
} from '../models/index';

export interface DeleteAvatarRequest {
    avatarId: string;
}

export interface GetAvatarRequest {
    avatarId: string;
}

export interface ListAvatarsRequest {
    scope?: ListAvatarsScopeEnum;
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class AvatarsApi extends runtime.BaseAPI {

    /**
     * Delete your own avatar (requires API key authentication)
     * Delete My Avatar
     */
    async deleteAvatarRaw(requestParameters: DeleteAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseAvatarDeleteResponse>> {
        if (requestParameters['avatarId'] == null) {
            throw new runtime.RequiredError(
                'avatarId',
                'Required parameter "avatarId" was null or undefined when calling deleteAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/avatars/{avatar_id}`;
        urlPath = urlPath.replace(`{${"avatar_id"}}`, encodeURIComponent(String(requestParameters['avatarId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseAvatarDeleteResponseFromJSON(jsonValue));
    }

    /**
     * Delete your own avatar (requires API key authentication)
     * Delete My Avatar
     */
    async deleteAvatar(requestParameters: DeleteAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseAvatarDeleteResponse> {
        const response = await this.deleteAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get detailed information about a specific avatar
     * Get Avatar Details
     */
    async getAvatarRaw(requestParameters: GetAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseAvatarResponse>> {
        if (requestParameters['avatarId'] == null) {
            throw new runtime.RequiredError(
                'avatarId',
                'Required parameter "avatarId" was null or undefined when calling getAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/avatars/{avatar_id}`;
        urlPath = urlPath.replace(`{${"avatar_id"}}`, encodeURIComponent(String(requestParameters['avatarId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseAvatarResponseFromJSON(jsonValue));
    }

    /**
     * Get detailed information about a specific avatar
     * Get Avatar Details
     */
    async getAvatar(requestParameters: GetAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseAvatarResponse> {
        const response = await this.getAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all public avatars with optional inclusion of your own avatars
     * List Avatars
     */
    async listAvatarsRaw(requestParameters: ListAvatarsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseAvatarResponse>> {
        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/avatars/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseAvatarResponseFromJSON(jsonValue));
    }

    /**
     * Get all public avatars with optional inclusion of your own avatars
     * List Avatars
     */
    async listAvatars(requestParameters: ListAvatarsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseAvatarResponse> {
        const response = await this.listAvatarsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListAvatarsScopeEnum = {
    All: 'all',
    Public: 'public',
    Private: 'private'
} as const;
export type ListAvatarsScopeEnum = typeof ListAvatarsScopeEnum[keyof typeof ListAvatarsScopeEnum];
