/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BrainCreate,
  HTTPValidationError,
} from '../models/index';
import {
    BrainCreateFromJSON,
    BrainCreateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateBrainRequest {
    brainCreate: BrainCreate;
}

export interface DeleteBrainRequest {
    brainId: string;
}

export interface ListBrainsRequest {
    scope?: ListBrainsScopeEnum;
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class BrainsApi extends runtime.BaseAPI {

    /**
     * Create a new brain
     */
    async createBrainRaw(requestParameters: CreateBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['brainCreate'] == null) {
            throw new runtime.RequiredError(
                'brainCreate',
                'Required parameter "brainCreate" was null or undefined when calling createBrain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/brains/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BrainCreateToJSON(requestParameters['brainCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create a new brain
     */
    async createBrain(requestParameters: CreateBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createBrainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a brain
     */
    async deleteBrainRaw(requestParameters: DeleteBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['brainId'] == null) {
            throw new runtime.RequiredError(
                'brainId',
                'Required parameter "brainId" was null or undefined when calling deleteBrain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/brains/{brain_id}`;
        urlPath = urlPath.replace(`{${"brain_id"}}`, encodeURIComponent(String(requestParameters['brainId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a brain
     */
    async deleteBrain(requestParameters: DeleteBrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteBrainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Brains - public API endpoint - API Key required for all scopes - Set `scope` to \"all\" to include your own Brains - Set `scope` to \"public\" to get only public Brains - Set `scope` to \"private\" to get only your own private Brains
     * List Brains
     */
    async listBrainsRaw(requestParameters: ListBrainsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/brains/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Brains - public API endpoint - API Key required for all scopes - Set `scope` to \"all\" to include your own Brains - Set `scope` to \"public\" to get only public Brains - Set `scope` to \"private\" to get only your own private Brains
     * List Brains
     */
    async listBrains(requestParameters: ListBrainsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listBrainsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListBrainsScopeEnum = {
    All: 'all',
    Public: 'public',
    Private: 'private'
} as const;
export type ListBrainsScopeEnum = typeof ListBrainsScopeEnum[keyof typeof ListBrainsScopeEnum];
