/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ListVoicesRequest {
    scope?: ListVoicesScopeEnum;
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class VoicesApi extends runtime.BaseAPI {

    /**
     * List voices - public API endpoint - API Key required for all scopes - Set `scope` to \"all\" to include your own voices - Set `scope` to \"public\" to get only public voices - Set `scope` to \"private\" to get only your own private voices
     * List Voices
     */
    async listVoicesRaw(requestParameters: ListVoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/voices/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List voices - public API endpoint - API Key required for all scopes - Set `scope` to \"all\" to include your own voices - Set `scope` to \"public\" to get only public voices - Set `scope` to \"private\" to get only your own private voices
     * List Voices
     */
    async listVoices(requestParameters: ListVoicesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listVoicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListVoicesScopeEnum = {
    All: 'all',
    Public: 'public',
    Private: 'private'
} as const;
export type ListVoicesScopeEnum = typeof ListVoicesScopeEnum[keyof typeof ListVoicesScopeEnum];
