/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SuccessResponseWidgetSessionResponse,
  WidgetSessionCreate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SuccessResponseWidgetSessionResponseFromJSON,
    SuccessResponseWidgetSessionResponseToJSON,
    WidgetSessionCreateFromJSON,
    WidgetSessionCreateToJSON,
} from '../models/index';

export interface CreateWidgetSessionRequest {
    widgetSessionCreate: WidgetSessionCreate;
}

export interface GetWidgetSessionStatusRequest {
    sessionId: string;
}

export interface RevokeWidgetSessionRequest {
    sessionId: string;
}

/**
 * 
 */
export class WidgetApi extends runtime.BaseAPI {

    /**
     * Generate a temporary session token for embedding the widget on external websites. This endpoint should be called by the customer\'s backend with their API key.
     * Create Widget Session
     */
    async createWidgetSessionRaw(requestParameters: CreateWidgetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseWidgetSessionResponse>> {
        if (requestParameters['widgetSessionCreate'] == null) {
            throw new runtime.RequiredError(
                'widgetSessionCreate',
                'Required parameter "widgetSessionCreate" was null or undefined when calling createWidgetSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/widget/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WidgetSessionCreateToJSON(requestParameters['widgetSessionCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseWidgetSessionResponseFromJSON(jsonValue));
    }

    /**
     * Generate a temporary session token for embedding the widget on external websites. This endpoint should be called by the customer\'s backend with their API key.
     * Create Widget Session
     */
    async createWidgetSession(requestParameters: CreateWidgetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseWidgetSessionResponse> {
        const response = await this.createWidgetSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check if a widget session is still valid
     * Get Widget Session Status
     */
    async getWidgetSessionStatusRaw(requestParameters: GetWidgetSessionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getWidgetSessionStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/widget/sessions/{session_id}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Check if a widget session is still valid
     * Get Widget Session Status
     */
    async getWidgetSessionStatus(requestParameters: GetWidgetSessionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getWidgetSessionStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke a widget session token before expiry
     * Revoke Widget Session
     */
    async revokeWidgetSessionRaw(requestParameters: RevokeWidgetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling revokeWidgetSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/widget/sessions/{session_id}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Revoke a widget session token before expiry
     * Revoke Widget Session
     */
    async revokeWidgetSession(requestParameters: RevokeWidgetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.revokeWidgetSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
