/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Brain } from './Brain';
import {
    BrainFromJSON,
    BrainFromJSONTyped,
    BrainToJSON,
    BrainToJSONTyped,
} from './Brain';
import type { Voice } from './Voice';
import {
    VoiceFromJSON,
    VoiceFromJSONTyped,
    VoiceToJSON,
    VoiceToJSONTyped,
} from './Voice';
import type { Avatar } from './Avatar';
import {
    AvatarFromJSON,
    AvatarFromJSONTyped,
    AvatarToJSON,
    AvatarToJSONTyped,
} from './Avatar';

/**
 * 
 * @export
 * @interface AgenticAvatarResponse
 */
export interface AgenticAvatarResponse {
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarResponse
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarResponse
     */
    avatarId: string;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarResponse
     */
    voiceId: string;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarResponse
     */
    brainId: string;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarResponse
     */
    id: string;
    /**
     * 
     * @type {Brain}
     * @memberof AgenticAvatarResponse
     */
    brain?: Brain | null;
    /**
     * 
     * @type {Voice}
     * @memberof AgenticAvatarResponse
     */
    voice?: Voice | null;
    /**
     * 
     * @type {Avatar}
     * @memberof AgenticAvatarResponse
     */
    avatar?: Avatar | null;
    /**
     * 
     * @type {Date}
     * @memberof AgenticAvatarResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AgenticAvatarResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the AgenticAvatarResponse interface.
 */
export function instanceOfAgenticAvatarResponse(value: object): value is AgenticAvatarResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatarId' in value) || value['avatarId'] === undefined) return false;
    if (!('voiceId' in value) || value['voiceId'] === undefined) return false;
    if (!('brainId' in value) || value['brainId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AgenticAvatarResponseFromJSON(json: any): AgenticAvatarResponse {
    return AgenticAvatarResponseFromJSONTyped(json, false);
}

export function AgenticAvatarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgenticAvatarResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'avatarId': json['avatar_id'],
        'voiceId': json['voice_id'],
        'brainId': json['brain_id'],
        'id': json['id'],
        'brain': json['brain'] == null ? undefined : BrainFromJSON(json['brain']),
        'voice': json['voice'] == null ? undefined : VoiceFromJSON(json['voice']),
        'avatar': json['avatar'] == null ? undefined : AvatarFromJSON(json['avatar']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function AgenticAvatarResponseToJSON(json: any): AgenticAvatarResponse {
    return AgenticAvatarResponseToJSONTyped(json, false);
}

export function AgenticAvatarResponseToJSONTyped(value?: AgenticAvatarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'user_id': value['userId'],
        'avatar_id': value['avatarId'],
        'voice_id': value['voiceId'],
        'brain_id': value['brainId'],
        'id': value['id'],
        'brain': BrainToJSON(value['brain']),
        'voice': VoiceToJSON(value['voice']),
        'avatar': AvatarToJSON(value['avatar']),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

