/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgenticAvatarCreate
 */
export interface AgenticAvatarCreate {
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarCreate
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarCreate
     */
    avatarId: string;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarCreate
     */
    voiceId: string;
    /**
     * 
     * @type {string}
     * @memberof AgenticAvatarCreate
     */
    brainId: string;
}

/**
 * Check if a given object implements the AgenticAvatarCreate interface.
 */
export function instanceOfAgenticAvatarCreate(value: object): value is AgenticAvatarCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatarId' in value) || value['avatarId'] === undefined) return false;
    if (!('voiceId' in value) || value['voiceId'] === undefined) return false;
    if (!('brainId' in value) || value['brainId'] === undefined) return false;
    return true;
}

export function AgenticAvatarCreateFromJSON(json: any): AgenticAvatarCreate {
    return AgenticAvatarCreateFromJSONTyped(json, false);
}

export function AgenticAvatarCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgenticAvatarCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'avatarId': json['avatar_id'],
        'voiceId': json['voice_id'],
        'brainId': json['brain_id'],
    };
}

export function AgenticAvatarCreateToJSON(json: any): AgenticAvatarCreate {
    return AgenticAvatarCreateToJSONTyped(json, false);
}

export function AgenticAvatarCreateToJSONTyped(value?: AgenticAvatarCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'user_id': value['userId'],
        'avatar_id': value['avatarId'],
        'voice_id': value['voiceId'],
        'brain_id': value['brainId'],
    };
}

