/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyResponse
 */
export interface ApiKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponse
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiKeyResponse
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ApiKeyResponse
     */
    rateLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiKeyResponse
     */
    rateLimitWindow?: number;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiKeyResponse
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponse
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponse
     */
    prefix: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    lastUsedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyResponse
     */
    lastUsedIp?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiKeyResponse
     */
    requestCount: number;
    /**
     * 
     * @type {object}
     * @memberof ApiKeyResponse
     */
    keyMetadata?: object | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the ApiKeyResponse interface.
 */
export function instanceOfApiKeyResponse(value: object): value is ApiKeyResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    if (!('requestCount' in value) || value['requestCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ApiKeyResponseFromJSON(json: any): ApiKeyResponse {
    return ApiKeyResponseFromJSONTyped(json, false);
}

export function ApiKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'name': json['name'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'rateLimit': json['rate_limit'] == null ? undefined : json['rate_limit'],
        'rateLimitWindow': json['rate_limit_window'] == null ? undefined : json['rate_limit_window'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'id': json['id'],
        'key': json['key'],
        'prefix': json['prefix'],
        'lastUsedAt': json['last_used_at'] == null ? undefined : (new Date(json['last_used_at'])),
        'lastUsedIp': json['last_used_ip'] == null ? undefined : json['last_used_ip'],
        'requestCount': json['request_count'],
        'keyMetadata': json['key_metadata'] == null ? undefined : json['key_metadata'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ApiKeyResponseToJSON(json: any): ApiKeyResponse {
    return ApiKeyResponseToJSONTyped(json, false);
}

export function ApiKeyResponseToJSONTyped(value?: ApiKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'name': value['name'],
        'scopes': value['scopes'],
        'rate_limit': value['rateLimit'],
        'rate_limit_window': value['rateLimitWindow'],
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'is_active': value['isActive'],
        'id': value['id'],
        'key': value['key'],
        'prefix': value['prefix'],
        'last_used_at': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
        'last_used_ip': value['lastUsedIp'],
        'request_count': value['requestCount'],
        'key_metadata': value['keyMetadata'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

