/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeyResponse } from './ApiKeyResponse';
import {
    ApiKeyResponseFromJSON,
    ApiKeyResponseFromJSONTyped,
    ApiKeyResponseToJSON,
    ApiKeyResponseToJSONTyped,
} from './ApiKeyResponse';

/**
 * 
 * @export
 * @interface ApiKeyValidationResponse
 */
export interface ApiKeyValidationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ApiKeyValidationResponse
     */
    valid: boolean;
    /**
     * 
     * @type {ApiKeyResponse}
     * @memberof ApiKeyValidationResponse
     */
    key?: ApiKeyResponse | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyValidationResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ApiKeyValidationResponse interface.
 */
export function instanceOfApiKeyValidationResponse(value: object): value is ApiKeyValidationResponse {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApiKeyValidationResponseFromJSON(json: any): ApiKeyValidationResponse {
    return ApiKeyValidationResponseFromJSONTyped(json, false);
}

export function ApiKeyValidationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyValidationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'],
        'key': json['key'] == null ? undefined : ApiKeyResponseFromJSON(json['key']),
        'message': json['message'],
    };
}

export function ApiKeyValidationResponseToJSON(json: any): ApiKeyValidationResponse {
    return ApiKeyValidationResponseToJSONTyped(json, false);
}

export function ApiKeyValidationResponseToJSONTyped(value?: ApiKeyValidationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'key': ApiKeyResponseToJSON(value['key']),
        'message': value['message'],
    };
}

