/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvatarDeleteResponse
 */
export interface AvatarDeleteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AvatarDeleteResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof AvatarDeleteResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarDeleteResponse
     */
    deletedId: string;
}

/**
 * Check if a given object implements the AvatarDeleteResponse interface.
 */
export function instanceOfAvatarDeleteResponse(value: object): value is AvatarDeleteResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('deletedId' in value) || value['deletedId'] === undefined) return false;
    return true;
}

export function AvatarDeleteResponseFromJSON(json: any): AvatarDeleteResponse {
    return AvatarDeleteResponseFromJSONTyped(json, false);
}

export function AvatarDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'deletedId': json['deleted_id'],
    };
}

export function AvatarDeleteResponseToJSON(json: any): AvatarDeleteResponse {
    return AvatarDeleteResponseToJSONTyped(json, false);
}

export function AvatarDeleteResponseToJSONTyped(value?: AvatarDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'deleted_id': value['deletedId'],
    };
}

