/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Avatar
 */
export interface Avatar {
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    gender: string;
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    occupation: string;
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    cdnUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    previewImage?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Avatar
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    userId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Avatar
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Avatar
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Avatar interface.
 */
export function instanceOfAvatar(value: object): value is Avatar {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('occupation' in value) || value['occupation'] === undefined) return false;
    if (!('cdnUrl' in value) || value['cdnUrl'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AvatarFromJSON(json: any): Avatar {
    return AvatarFromJSONTyped(json, false);
}

export function AvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Avatar {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'gender': json['gender'],
        'occupation': json['occupation'],
        'cdnUrl': json['cdn_url'],
        'previewImage': json['preview_image'] == null ? undefined : json['preview_image'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'id': json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function AvatarToJSON(json: any): Avatar {
    return AvatarToJSONTyped(json, false);
}

export function AvatarToJSONTyped(value?: Avatar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'gender': value['gender'],
        'occupation': value['occupation'],
        'cdn_url': value['cdnUrl'],
        'preview_image': value['previewImage'],
        'is_public': value['isPublic'],
        'id': value['id'],
        'user_id': value['userId'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

