/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrainCreate
 */
export interface BrainCreate {
    /**
     * 
     * @type {string}
     * @memberof BrainCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BrainCreate
     */
    systemPrompt: string;
    /**
     * 
     * @type {string}
     * @memberof BrainCreate
     */
    llmName: string;
    /**
     * 
     * @type {string}
     * @memberof BrainCreate
     */
    knowledgeBaseId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BrainCreate
     */
    isPublic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BrainCreate
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the BrainCreate interface.
 */
export function instanceOfBrainCreate(value: object): value is BrainCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('systemPrompt' in value) || value['systemPrompt'] === undefined) return false;
    if (!('llmName' in value) || value['llmName'] === undefined) return false;
    return true;
}

export function BrainCreateFromJSON(json: any): BrainCreate {
    return BrainCreateFromJSONTyped(json, false);
}

export function BrainCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrainCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'systemPrompt': json['system_prompt'],
        'llmName': json['llm_name'],
        'knowledgeBaseId': json['knowledge_base_id'] == null ? undefined : json['knowledge_base_id'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function BrainCreateToJSON(json: any): BrainCreate {
    return BrainCreateToJSONTyped(json, false);
}

export function BrainCreateToJSONTyped(value?: BrainCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'system_prompt': value['systemPrompt'],
        'llm_name': value['llmName'],
        'knowledge_base_id': value['knowledgeBaseId'],
        'is_public': value['isPublic'],
        'is_active': value['isActive'],
    };
}

