/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Brain
 */
export interface Brain {
    /**
     * 
     * @type {string}
     * @memberof Brain
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Brain
     */
    systemPrompt: string;
    /**
     * 
     * @type {string}
     * @memberof Brain
     */
    llmName: string;
    /**
     * 
     * @type {string}
     * @memberof Brain
     */
    knowledgeBaseId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Brain
     */
    isPublic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Brain
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Brain
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Brain
     */
    userId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Brain
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Brain
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Brain interface.
 */
export function instanceOfBrain(value: object): value is Brain {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('systemPrompt' in value) || value['systemPrompt'] === undefined) return false;
    if (!('llmName' in value) || value['llmName'] === undefined) return false;
    return true;
}

export function BrainFromJSON(json: any): Brain {
    return BrainFromJSONTyped(json, false);
}

export function BrainFromJSONTyped(json: any, ignoreDiscriminator: boolean): Brain {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'systemPrompt': json['system_prompt'],
        'llmName': json['llm_name'],
        'knowledgeBaseId': json['knowledge_base_id'] == null ? undefined : json['knowledge_base_id'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function BrainToJSON(json: any): Brain {
    return BrainToJSONTyped(json, false);
}

export function BrainToJSONTyped(value?: Brain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'system_prompt': value['systemPrompt'],
        'llm_name': value['llmName'],
        'knowledge_base_id': value['knowledgeBaseId'],
        'is_public': value['isPublic'],
        'is_active': value['isActive'],
        'id': value['id'],
        'user_id': value['userId'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

