/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination metadata.
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * Current page number
     * @type {number}
     * @memberof PaginationMeta
     */
    page: number;
    /**
     * Items per page
     * @type {number}
     * @memberof PaginationMeta
     */
    pageSize: number;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginationMeta
     */
    total: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginationMeta
     */
    totalPages: number;
    /**
     * Has next page
     * @type {boolean}
     * @memberof PaginationMeta
     */
    hasNext: boolean;
    /**
     * Has previous page
     * @type {boolean}
     * @memberof PaginationMeta
     */
    hasPrev: boolean;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('hasPrev' in value) || value['hasPrev'] === undefined) return false;
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['page_size'],
        'total': json['total'],
        'totalPages': json['total_pages'],
        'hasNext': json['has_next'],
        'hasPrev': json['has_prev'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'page_size': value['pageSize'],
        'total': value['total'],
        'total_pages': value['totalPages'],
        'has_next': value['hasNext'],
        'has_prev': value['hasPrev'],
    };
}

