/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { AgenticAvatarResponse } from './AgenticAvatarResponse';
import {
    AgenticAvatarResponseFromJSON,
    AgenticAvatarResponseFromJSONTyped,
    AgenticAvatarResponseToJSON,
    AgenticAvatarResponseToJSONTyped,
} from './AgenticAvatarResponse';

/**
 * 
 * @export
 * @interface PaginatedResponseAgenticAvatarResponse
 */
export interface PaginatedResponseAgenticAvatarResponse {
    /**
     * 
     * @type {Array<AgenticAvatarResponse>}
     * @memberof PaginatedResponseAgenticAvatarResponse
     */
    data: Array<AgenticAvatarResponse>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedResponseAgenticAvatarResponse
     */
    meta: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResponseAgenticAvatarResponse interface.
 */
export function instanceOfPaginatedResponseAgenticAvatarResponse(value: object): value is PaginatedResponseAgenticAvatarResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function PaginatedResponseAgenticAvatarResponseFromJSON(json: any): PaginatedResponseAgenticAvatarResponse {
    return PaginatedResponseAgenticAvatarResponseFromJSONTyped(json, false);
}

export function PaginatedResponseAgenticAvatarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseAgenticAvatarResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AgenticAvatarResponseFromJSON)),
        'meta': PaginationMetaFromJSON(json['meta']),
    };
}

export function PaginatedResponseAgenticAvatarResponseToJSON(json: any): PaginatedResponseAgenticAvatarResponse {
    return PaginatedResponseAgenticAvatarResponseToJSONTyped(json, false);
}

export function PaginatedResponseAgenticAvatarResponseToJSONTyped(value?: PaginatedResponseAgenticAvatarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(AgenticAvatarResponseToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

