/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { AvatarResponse } from './AvatarResponse';
import {
    AvatarResponseFromJSON,
    AvatarResponseFromJSONTyped,
    AvatarResponseToJSON,
    AvatarResponseToJSONTyped,
} from './AvatarResponse';

/**
 * 
 * @export
 * @interface PaginatedResponseAvatarResponse
 */
export interface PaginatedResponseAvatarResponse {
    /**
     * 
     * @type {Array<AvatarResponse>}
     * @memberof PaginatedResponseAvatarResponse
     */
    data: Array<AvatarResponse>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedResponseAvatarResponse
     */
    meta: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResponseAvatarResponse interface.
 */
export function instanceOfPaginatedResponseAvatarResponse(value: object): value is PaginatedResponseAvatarResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function PaginatedResponseAvatarResponseFromJSON(json: any): PaginatedResponseAvatarResponse {
    return PaginatedResponseAvatarResponseFromJSONTyped(json, false);
}

export function PaginatedResponseAvatarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseAvatarResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AvatarResponseFromJSON)),
        'meta': PaginationMetaFromJSON(json['meta']),
    };
}

export function PaginatedResponseAvatarResponseToJSON(json: any): PaginatedResponseAvatarResponse {
    return PaginatedResponseAvatarResponseToJSONTyped(json, false);
}

export function PaginatedResponseAvatarResponseToJSONTyped(value?: PaginatedResponseAvatarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(AvatarResponseToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

