/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeyValidationResponse } from './ApiKeyValidationResponse';
import {
    ApiKeyValidationResponseFromJSON,
    ApiKeyValidationResponseFromJSONTyped,
    ApiKeyValidationResponseToJSON,
    ApiKeyValidationResponseToJSONTyped,
} from './ApiKeyValidationResponse';

/**
 * 
 * @export
 * @interface SuccessResponseApiKeyValidationResponse
 */
export interface SuccessResponseApiKeyValidationResponse {
    /**
     * 
     * @type {ApiKeyValidationResponse}
     * @memberof SuccessResponseApiKeyValidationResponse
     */
    data: ApiKeyValidationResponse;
    /**
     * 
     * @type {object}
     * @memberof SuccessResponseApiKeyValidationResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the SuccessResponseApiKeyValidationResponse interface.
 */
export function instanceOfSuccessResponseApiKeyValidationResponse(value: object): value is SuccessResponseApiKeyValidationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SuccessResponseApiKeyValidationResponseFromJSON(json: any): SuccessResponseApiKeyValidationResponse {
    return SuccessResponseApiKeyValidationResponseFromJSONTyped(json, false);
}

export function SuccessResponseApiKeyValidationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessResponseApiKeyValidationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ApiKeyValidationResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function SuccessResponseApiKeyValidationResponseToJSON(json: any): SuccessResponseApiKeyValidationResponse {
    return SuccessResponseApiKeyValidationResponseToJSONTyped(json, false);
}

export function SuccessResponseApiKeyValidationResponseToJSONTyped(value?: SuccessResponseApiKeyValidationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ApiKeyValidationResponseToJSON(value['data']),
        'meta': value['meta'],
    };
}

