/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WidgetSessionResponse } from './WidgetSessionResponse';
import {
    WidgetSessionResponseFromJSON,
    WidgetSessionResponseFromJSONTyped,
    WidgetSessionResponseToJSON,
    WidgetSessionResponseToJSONTyped,
} from './WidgetSessionResponse';

/**
 * 
 * @export
 * @interface SuccessResponseWidgetSessionResponse
 */
export interface SuccessResponseWidgetSessionResponse {
    /**
     * 
     * @type {WidgetSessionResponse}
     * @memberof SuccessResponseWidgetSessionResponse
     */
    data: WidgetSessionResponse;
    /**
     * 
     * @type {object}
     * @memberof SuccessResponseWidgetSessionResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the SuccessResponseWidgetSessionResponse interface.
 */
export function instanceOfSuccessResponseWidgetSessionResponse(value: object): value is SuccessResponseWidgetSessionResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SuccessResponseWidgetSessionResponseFromJSON(json: any): SuccessResponseWidgetSessionResponse {
    return SuccessResponseWidgetSessionResponseFromJSONTyped(json, false);
}

export function SuccessResponseWidgetSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessResponseWidgetSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': WidgetSessionResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function SuccessResponseWidgetSessionResponseToJSON(json: any): SuccessResponseWidgetSessionResponse {
    return SuccessResponseWidgetSessionResponseToJSONTyped(json, false);
}

export function SuccessResponseWidgetSessionResponseToJSONTyped(value?: SuccessResponseWidgetSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': WidgetSessionResponseToJSON(value['data']),
        'meta': value['meta'],
    };
}

