/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvatarResponse } from './AvatarResponse';
import {
    AvatarResponseFromJSON,
    AvatarResponseFromJSONTyped,
    AvatarResponseToJSON,
    AvatarResponseToJSONTyped,
} from './AvatarResponse';

/**
 * 
 * @export
 * @interface SuccessResponseAvatarResponse
 */
export interface SuccessResponseAvatarResponse {
    /**
     * 
     * @type {AvatarResponse}
     * @memberof SuccessResponseAvatarResponse
     */
    data: AvatarResponse;
    /**
     * 
     * @type {object}
     * @memberof SuccessResponseAvatarResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the SuccessResponseAvatarResponse interface.
 */
export function instanceOfSuccessResponseAvatarResponse(value: object): value is SuccessResponseAvatarResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SuccessResponseAvatarResponseFromJSON(json: any): SuccessResponseAvatarResponse {
    return SuccessResponseAvatarResponseFromJSONTyped(json, false);
}

export function SuccessResponseAvatarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessResponseAvatarResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AvatarResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function SuccessResponseAvatarResponseToJSON(json: any): SuccessResponseAvatarResponse {
    return SuccessResponseAvatarResponseToJSONTyped(json, false);
}

export function SuccessResponseAvatarResponseToJSONTyped(value?: SuccessResponseAvatarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AvatarResponseToJSON(value['data']),
        'meta': value['meta'],
    };
}

