/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgenticAvatarResponse } from './AgenticAvatarResponse';
import {
    AgenticAvatarResponseFromJSON,
    AgenticAvatarResponseFromJSONTyped,
    AgenticAvatarResponseToJSON,
    AgenticAvatarResponseToJSONTyped,
} from './AgenticAvatarResponse';

/**
 * 
 * @export
 * @interface SuccessResponseAgenticAvatarResponse
 */
export interface SuccessResponseAgenticAvatarResponse {
    /**
     * 
     * @type {AgenticAvatarResponse}
     * @memberof SuccessResponseAgenticAvatarResponse
     */
    data: AgenticAvatarResponse;
    /**
     * 
     * @type {object}
     * @memberof SuccessResponseAgenticAvatarResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the SuccessResponseAgenticAvatarResponse interface.
 */
export function instanceOfSuccessResponseAgenticAvatarResponse(value: object): value is SuccessResponseAgenticAvatarResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SuccessResponseAgenticAvatarResponseFromJSON(json: any): SuccessResponseAgenticAvatarResponse {
    return SuccessResponseAgenticAvatarResponseFromJSONTyped(json, false);
}

export function SuccessResponseAgenticAvatarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessResponseAgenticAvatarResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AgenticAvatarResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function SuccessResponseAgenticAvatarResponseToJSON(json: any): SuccessResponseAgenticAvatarResponse {
    return SuccessResponseAgenticAvatarResponseToJSONTyped(json, false);
}

export function SuccessResponseAgenticAvatarResponseToJSONTyped(value?: SuccessResponseAgenticAvatarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AgenticAvatarResponseToJSON(value['data']),
        'meta': value['meta'],
    };
}

