/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvatarDeleteResponse } from './AvatarDeleteResponse';
import {
    AvatarDeleteResponseFromJSON,
    AvatarDeleteResponseFromJSONTyped,
    AvatarDeleteResponseToJSON,
    AvatarDeleteResponseToJSONTyped,
} from './AvatarDeleteResponse';

/**
 * 
 * @export
 * @interface SuccessResponseAvatarDeleteResponse
 */
export interface SuccessResponseAvatarDeleteResponse {
    /**
     * 
     * @type {AvatarDeleteResponse}
     * @memberof SuccessResponseAvatarDeleteResponse
     */
    data: AvatarDeleteResponse;
    /**
     * 
     * @type {object}
     * @memberof SuccessResponseAvatarDeleteResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the SuccessResponseAvatarDeleteResponse interface.
 */
export function instanceOfSuccessResponseAvatarDeleteResponse(value: object): value is SuccessResponseAvatarDeleteResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SuccessResponseAvatarDeleteResponseFromJSON(json: any): SuccessResponseAvatarDeleteResponse {
    return SuccessResponseAvatarDeleteResponseFromJSONTyped(json, false);
}

export function SuccessResponseAvatarDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessResponseAvatarDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AvatarDeleteResponseFromJSON(json['data']),
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function SuccessResponseAvatarDeleteResponseToJSON(json: any): SuccessResponseAvatarDeleteResponse {
    return SuccessResponseAvatarDeleteResponseToJSONTyped(json, false);
}

export function SuccessResponseAvatarDeleteResponseToJSONTyped(value?: SuccessResponseAvatarDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AvatarDeleteResponseToJSON(value['data']),
        'meta': value['meta'],
    };
}

