/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Voice
 */
export interface Voice {
    /**
     * 
     * @type {string}
     * @memberof Voice
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Voice
     */
    gender: string;
    /**
     * 
     * @type {string}
     * @memberof Voice
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Voice
     */
    elevenlabsVoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof Voice
     */
    previewUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Voice
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Voice
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Voice
     */
    userId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Voice
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Voice
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the Voice interface.
 */
export function instanceOfVoice(value: object): value is Voice {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('elevenlabsVoiceId' in value) || value['elevenlabsVoiceId'] === undefined) return false;
    return true;
}

export function VoiceFromJSON(json: any): Voice {
    return VoiceFromJSONTyped(json, false);
}

export function VoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Voice {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'gender': json['gender'],
        'description': json['description'] == null ? undefined : json['description'],
        'elevenlabsVoiceId': json['elevenlabs_voice_id'],
        'previewUrl': json['preview_url'] == null ? undefined : json['preview_url'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function VoiceToJSON(json: any): Voice {
    return VoiceToJSONTyped(json, false);
}

export function VoiceToJSONTyped(value?: Voice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'gender': value['gender'],
        'description': value['description'],
        'elevenlabs_voice_id': value['elevenlabsVoiceId'],
        'preview_url': value['previewUrl'],
        'is_public': value['isPublic'],
        'id': value['id'],
        'user_id': value['userId'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

