/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetSessionCreate
 */
export interface WidgetSessionCreate {
    /**
     * 
     * @type {string}
     * @memberof WidgetSessionCreate
     */
    agenticAvatarId: string;
    /**
     * 
     * @type {object}
     * @memberof WidgetSessionCreate
     */
    userMetadata?: object | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WidgetSessionCreate
     */
    allowedOrigins?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof WidgetSessionCreate
     */
    audioOnly?: boolean;
}

/**
 * Check if a given object implements the WidgetSessionCreate interface.
 */
export function instanceOfWidgetSessionCreate(value: object): value is WidgetSessionCreate {
    if (!('agenticAvatarId' in value) || value['agenticAvatarId'] === undefined) return false;
    return true;
}

export function WidgetSessionCreateFromJSON(json: any): WidgetSessionCreate {
    return WidgetSessionCreateFromJSONTyped(json, false);
}

export function WidgetSessionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetSessionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'agenticAvatarId': json['agentic_avatar_id'],
        'userMetadata': json['user_metadata'] == null ? undefined : json['user_metadata'],
        'allowedOrigins': json['allowed_origins'] == null ? undefined : json['allowed_origins'],
        'audioOnly': json['audio_only'] == null ? undefined : json['audio_only'],
    };
}

export function WidgetSessionCreateToJSON(json: any): WidgetSessionCreate {
    return WidgetSessionCreateToJSONTyped(json, false);
}

export function WidgetSessionCreateToJSONTyped(value?: WidgetSessionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agentic_avatar_id': value['agenticAvatarId'],
        'user_metadata': value['userMetadata'],
        'allowed_origins': value['allowedOrigins'],
        'audio_only': value['audioOnly'],
    };
}

