/* tslint:disable */
/* eslint-disable */
/**
 * KonPro Public API
 * High-performance public API with Valkey cache
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetSessionResponse
 */
export interface WidgetSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof WidgetSessionResponse
     */
    sessionToken: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetSessionResponse
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetSessionResponse
     */
    expiresAt: string;
    /**
     * 
     * @type {number}
     * @memberof WidgetSessionResponse
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof WidgetSessionResponse
     */
    websocketUrl: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetSessionResponse
     */
    userId: string;
    /**
     * 
     * @type {object}
     * @memberof WidgetSessionResponse
     */
    avatar: object;
    /**
     * 
     * @type {boolean}
     * @memberof WidgetSessionResponse
     */
    audioOnly?: boolean;
}

/**
 * Check if a given object implements the WidgetSessionResponse interface.
 */
export function instanceOfWidgetSessionResponse(value: object): value is WidgetSessionResponse {
    if (!('sessionToken' in value) || value['sessionToken'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('websocketUrl' in value) || value['websocketUrl'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    return true;
}

export function WidgetSessionResponseFromJSON(json: any): WidgetSessionResponse {
    return WidgetSessionResponseFromJSONTyped(json, false);
}

export function WidgetSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionToken': json['session_token'],
        'sessionId': json['session_id'],
        'expiresAt': json['expires_at'],
        'expiresIn': json['expires_in'],
        'websocketUrl': json['websocket_url'],
        'userId': json['user_id'],
        'avatar': json['avatar'],
        'audioOnly': json['audio_only'] == null ? undefined : json['audio_only'],
    };
}

export function WidgetSessionResponseToJSON(json: any): WidgetSessionResponse {
    return WidgetSessionResponseToJSONTyped(json, false);
}

export function WidgetSessionResponseToJSONTyped(value?: WidgetSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session_token': value['sessionToken'],
        'session_id': value['sessionId'],
        'expires_at': value['expiresAt'],
        'expires_in': value['expiresIn'],
        'websocket_url': value['websocketUrl'],
        'user_id': value['userId'],
        'avatar': value['avatar'],
        'audio_only': value['audioOnly'],
    };
}

